/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNavigation: typeof import('./src/components/BottomNavigation.vue')['default']
    Faqs: typeof import('./src/components/Faqs.vue')['default']
    FooterBg: typeof import('./src/components/FooterBg.vue')['default']
    IconGroup: typeof import('./src/components/IconGroup.vue')['default']
    IconList: typeof import('./src/components/IconList.vue')['default']
    MusicPlayer: typeof import('./src/components/MusicPlayer.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidedLayout: typeof import('./src/components/SidedLayout.vue')['default']
  }
}
